name: Setup Dependencies
description: Installs dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "18.19.0"
        cache: npm
    - run: npm ci
      shell: bash
