name: Deploy to Firebase Hosting on merge
on:
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        with:
            channelId: live
